# Workflow name
name: dynamic workflow

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    inputs:
      index_document:
        description: 'Name of the index document'
        required: true
        default: 'index.html'
      error_document:
        description: 'Name of error document' 
        required: true
        default: 'error.html'

env:
  BUCKET_NAME: website-james-artifacts
jobs:
  builds:  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Create CloudFormation Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: uda-james-artifact
        template: udatest.yml
        no-fail-on-empty-changeset: "1"

    - name: Upload file to S3 bucket
      run: |
        aws cloudformation describe-stacks \
          --stack-name uda-james-artifact \
          --query 'Stacks[0].Outputs[?OutputKey=='ArtifactBucketWebsiteURL']'.OutputValue' \
          --output text

        